apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mpdavis/homelab.git
        revision: HEAD
        files:
          - path: apps/*/argocd.json
  template:
    metadata:
      name: "{{.path.basename}}"
      labels:
        tier: apps
        category: "{{.category}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/mpdavis/homelab.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
