kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: grafana-admin
      userKey: admin-user
      passwordKey: admin-password
    initChownData:
      enabled: false
    securityContext:
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472
    persistence:
      enabled: true
      storageClassName: local-path
      size: 2Gi
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-gateway.loki.svc.cluster.local
        access: proxy
        isDefault: false

  prometheus:
    prometheusSpec:
      retention: 30d
      retentionSize: 10GB
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 2Gi

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
