---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base development packages
  ansible.builtin.apt:
    name: "{{ devbox_packages }}"
    state: present

- name: Link fd-find to fd
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
