apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - audiobookshelf
  - dispatcharr
  - ecm
  - emby
  - game-thumbs
  - listenarr
  - podfetch
  - streamflow
  - teamarr
