---
- name: Deploy subscription nag removal script
  ansible.builtin.template:
    src: pve-remove-nag.sh.j2
    dest: /usr/local/bin/pve-remove-nag.sh
    mode: "0755"

- name: Run nag removal script
  ansible.builtin.command: /usr/local/bin/pve-remove-nag.sh
  register: pve_nag_removal
  changed_when: "'patched' in pve_nag_removal.stdout"

- name: Install apt hook to re-apply nag removal after updates
  ansible.builtin.template:
    src: no-nag-script.j2
    dest: /etc/apt/apt.conf.d/no-nag-script
    mode: "0644"
