apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: recyclarr-secrets
  data:
    - secretKey: sonarr-api-key
      remoteRef:
        key: ${BWS_SONARR_API_KEY}
    - secretKey: radarr-api-key
      remoteRef:
        key: ${BWS_RADARR_API_KEY}
