apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - configmap.yaml
  - external-secret.yaml
  - rbac.yaml
  - pvc.yaml
  - helmrelease.yaml
  - ingressroute.yaml
