apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      nodeSelector:
        node-type: vm
      runtimeClassName: nvidia
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:latest
          ports:
            - containerPort: 9191
              name: http
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: DISPATCHARR_ENV
              value: aio
            - name: TZ
              value: ${TZ}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-data
