apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ollama
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ollama.mpdavis.com`)
      kind: Rule
      services:
        - name: ollama
          port: 11434
  tls: {}
