apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: game-thumbs
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "~5.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
    crds: CreateReplace
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/sethwv/game-thumbs
              tag: v2.2.0
            env:
              TZ: ${TZ}
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 3000
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 3000
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    persistence:
      cache:
        existingClaim: game-thumbs
        globalMounts:
          - path: /app/.cache
