apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-data
  resources:
    requests:
      storage: 1Gi
