apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: trek-secrets
  data:
    - secretKey: encryption-key
      remoteRef:
        key: ${BWS_TREK_ENCRYPTION_KEY}
