---
- name: Wait for cloud-init to finish
  ansible.builtin.command: cloud-init status --wait
  changed_when: false
  check_mode: false
  failed_when: common_cloud_init_result.rc not in [0, 2]
  register: common_cloud_init_result

- name: Write resolv.conf without search domain
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - nfs-common
    state: present
