apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - mousehole-external-secret.yaml
  - pvc.yaml
  - mousehole-pvc.yaml
  - deployment.yaml
  - service.yaml
  - mousehole-service.yaml
  - ingressroute.yaml
  - mousehole-ingressroute.yaml
