all:
  vars:
    ansible_user: michael
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    k3s_server:
      hosts:
        k3s-server:
          ansible_host: 10.0.1.50
          node_type: lxc
    k3s_agent:
      hosts:
        k3s-agent-1:
          ansible_host: 10.0.1.51
          node_type: lxc
        k3s-agent-gpu:
          ansible_host: 10.0.1.52
          node_type: vm
    k3s_cluster:
      children:
        k3s_server:
        k3s_agent:
      vars:
        k3s_server_ip: 10.0.1.50
