apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonvpn-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: protonvpn-credentials
  data:
    - secretKey: openvpn-user
      remoteRef:
        key: ${BWS_PROTONVPN_OPENVPN_USER}
    - secretKey: openvpn-password
      remoteRef:
        key: ${BWS_PROTONVPN_OPENVPN_PASSWORD}
