apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: protonvpn-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: protonvpn-credentials
  data:
    - secretKey: openvpn-user
      remoteRef:
        key: b1ddb5fb-97f3-4f03-a135-b4590133ba62
    - secretKey: openvpn-password
      remoteRef:
        key: b05e6988-7ece-4d13-97b2-b4590133d4c0
