apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: github-token
  data:
    - secretKey: token
      remoteRef:
        key: 6a623ba5-dc2b-4eea-b989-b46500f1c995
