apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: github-token
  data:
    - secretKey: token
      remoteRef:
        key: ${BWS_GITHUB_TOKEN}
