apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
  data:
    - secretKey: encryption-key
      remoteRef:
        key: ${BWS_N8N_ENCRYPTION_KEY}
