apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mousehole-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: mousehole-auth
  data:
    - secretKey: auth-password
      remoteRef:
        key: ${BWS_MOUSEHOLE_AUTH_PASSWORD}
