apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
data:
  configuration.yml: |
    server:
      address: 'tcp4://:9091'

    log:
      level: info

    theme: auto

    totp:
      disable: false
      issuer: ${DOMAIN}

    authentication_backend:
      file:
        path: /config/users_database.yml
        password:
          algorithm: argon2
          argon2:
            variant: argon2id
            iterations: 3
            memory: 65536
            parallelism: 4
            key_length: 32
            salt_length: 16

    access_control:
      default_policy: deny
      rules:
        - domain: '*.${DOMAIN}'
          policy: one_factor

    session:
      name: authelia_session
      cookies:
        - domain: ${DOMAIN}
          authelia_url: https://auth.${DOMAIN}

    regulation:
      max_retries: 5
      find_time: 2m
      ban_time: 5m

    storage:
      local:
        path: /data/db.sqlite3

    notifier:
      disable_startup_check: false
      filesystem:
        filename: /data/notification.txt
