apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-users
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authelia-users
    template:
      data:
        users_database.yml: |
          users:
            michael:
              disabled: false
              displayname: Michael
              email: michael@mpdavis.com
              password: '{{ .password_hash }}'
              groups:
                - admins
  data:
    - secretKey: password_hash
      remoteRef:
        key: 4544a484-7e6e-4543-9e0b-b4600109167d
