apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: ${BWS_AUTHELIA_JWT_SECRET}
    - secretKey: SESSION_SECRET
      remoteRef:
        key: ${BWS_AUTHELIA_SESSION_SECRET}
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: ${BWS_AUTHELIA_STORAGE_ENCRYPTION_KEY}
