apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: e2f00c0f-09cf-4cce-a955-b4600104fe8a
    - secretKey: SESSION_SECRET
      remoteRef:
        key: 855976cf-4f8b-42f0-b6bf-b46001053108
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: 428f90ae-7a5f-4450-a0e2-b460010545d7
