apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authelia-users
    template:
      data:
        users_database.yml: |
          users:
            michael:
              disabled: false
              displayname: Michael
              email: ${EMAIL}
              password: '{{ .password_hash }}'
              groups:
                - admins
  data:
    - secretKey: password_hash
      remoteRef:
        key: ${BWS_AUTHELIA_PASSWORD_HASH}
