apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teamarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`teamarr.${DOMAIN}`)
      kind: Rule
      middlewares:
        - name: authentik-forward-auth
          namespace: authentik
      services:
        - name: teamarr
          port: 9195
  tls: {}
