apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podfetch
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`podfetch.mpdavis.com`)
      kind: Rule
      services:
        - name: podfetch
          port: 8000
  tls: {}
