apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mpdavis-com
  namespace: traefik
spec:
  secretName: wildcard-mpdavis-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
