---
- name: Setup Gitea git mirror
  hosts: git_mirror
  become: true
  vars_prompt:
    - name: gitea_admin_user
      prompt: "Gitea admin username"
      default: "michael"
      private: false
    - name: gitea_admin_password
      prompt: "Gitea admin password"
      private: true
    - name: gitea_admin_email
      prompt: "Gitea admin email"
      default: "michael@mpdavis.com"
      private: false
  roles:
    - gitea
