apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-secrets.yaml
  - flux-operator.yaml
  - metallb.yaml
  - traefik.yaml
  - monitoring.yaml
  - loki.yaml
  - promtail.yaml
  - nfs-data.yaml
  - nfs-homelab.yaml
