apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - external-secret.yaml
  - blueprint-paperless.yaml
  - blueprint-forward-auth.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - middleware.yaml
