apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Order: external-secret → pvc → helmrelease → ingressroute
  - external-secret.yaml
  - pvc.yaml
  - helmrelease.yaml
  - ingressroute.yaml
