apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-ntfy
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: alertmanager-ntfy
  data:
    - secretKey: token
      remoteRef:
        key: ${BWS_NTFY_ALERTMANAGER_TOKEN}
