apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-admin
  data:
    - secretKey: admin-user
      remoteRef:
        key: 5d21d6d4-5452-4a20-88fc-b4510146bcc9
    - secretKey: admin-password
      remoteRef:
        key: 84b2fe83-0a83-4b84-8f5d-b3e001210112
