apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret-grafana.yaml
  - ingress-grafana.yaml
  - dashboard-dcgm.yaml
  - node-disk-alerts.yaml
configMapGenerator:
  - name: grafana-dashboard-ecowitt
    namespace: monitoring
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - ecowitt-dashboard.json
