apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.mpdavis.com`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
  tls: {}
