apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - external-secrets
  - cert-manager
  - metallb
  - traefik
  - nfs-data
  - nfs-homelab
  - monitoring
  - loki
