apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: protonvpn-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: protonvpn-credentials
  data:
    - secretKey: openvpn-user
      remoteRef:
        key: REPLACE_WITH_BITWARDEN_UUID_FOR_OPENVPN_USER
    - secretKey: openvpn-password
      remoteRef:
        key: REPLACE_WITH_BITWARDEN_UUID_FOR_OPENVPN_PASSWORD
