apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
data:
  recyclarr.yml: |
    sonarr:
      web-1080p:
        base_url: http://sonarr:8989
        api_key: !env_var SONARR_API_KEY
        include:
          - template: web-1080p

    radarr:
      hd-bluray-web:
        base_url: http://radarr:7878
        api_key: !env_var RADARR_API_KEY
        include:
          - template: hd-bluray-web
