apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: recyclarr-secrets
  data:
    - secretKey: sonarr-api-key
      remoteRef:
        key: d84fd750-7fc2-45bf-8c91-b3e001210193
    - secretKey: radarr-api-key
      remoteRef:
        key: 9f883764-3296-4f58-9f0f-b3e001213e2a
