apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: audiobookshelf
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`audiobookshelf.mpdavis.com`)
      kind: Rule
      services:
        - name: audiobookshelf
          port: 3000
  tls: {}
