apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dispatcharr
  - ecm
  - emby
  - hello-world
  - homepage
  - prowlarr
  - qbittorrent
  - radarr
  - seerr
  - sonarr
  - teamarr
