traefik:
  ingressClass:
    enabled: true
    isDefaultClass: true

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
      publishedService:
        enabled: true

  service:
    type: LoadBalancer

  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
