apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      runtimeClassName: nvidia
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:latest@sha256:e764cd3fb3a4b14e0c96eeb830cce645b44ef0a2494838e21462c71dde5abeb4
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 9191
              name: http
          env:
            - name: DISPATCHARR_ENV
              value: aio
            - name: TZ
              value: ${TZ}
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-data
