apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcharr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      runtimeClassName: nvidia
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:latest@sha256:f2b5ea3128b0513feb07efee7539ad546f3ba3a9095f19936f446f75b8baa894
          ports:
            - containerPort: 9191
              name: http
          env:
            - name: DISPATCHARR_ENV
              value: aio
            - name: TZ
              value: ${TZ}
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-data
